### ISSUE TITLE
Error: Cannot set value to a final field 

### ISSUE THREAD

**Issue by pprossi** [rherrmann/gonsole#73]
Hi,

i get allways error messages on using Gonsole.
Is it a Configuration Problem in my setup?

```
vdpolizei-sw> help
Press Ctrl+Space for content assist
Press Up for command history

Available Commands
------------------
java.lang.IllegalStateException: Cannot set value to a final field 'com.codeaffine.gonsole.internal.interpreter.CommandInfo.arguments'.
	at org.kohsuke.args4j.spi.Setters.create(Setters.java:32)
	at org.kohsuke.args4j.ClassParser.parse(ClassParser.java:38)
	at org.kohsuke.args4j.CmdLineParser.<init>(CmdLineParser.java:96)
	at org.kohsuke.args4j.CmdLineParser.<init>(CmdLineParser.java:71)
	at org.eclipse.jgit.pgm.opt.CmdLineParser.<init>(CmdLineParser.java:133)
	at org.eclipse.jgit.pgm.opt.CmdLineParser.<init>(CmdLineParser.java:116)
	at com.codeaffine.gonsole.internal.interpreter.CommandLineParser.getCommandInfo(CommandLineParser.java:112)
	at com.codeaffine.gonsole.internal.interpreter.CommandLineParser.getUsage(CommandLineParser.java:58)
	at com.codeaffine.gonsole.internal.contentassist.GitCommandContentProposalProvider.toProposal(GitCommandContentProposalProvider.java:61)
	at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
	at java.util.HashMap$KeySpliterator.forEachRemaining(Unknown Source)
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source)
	at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
	at java.util.stream.ReferencePipeline.collect(Unknown Source)
	at com.codeaffine.gonsole.internal.contentassist.GitCommandContentProposalProvider.getCommandProposals(GitCommandContentProposalProvider.java:45)
	at com.codeaffine.gonsole.internal.contentassist.GitCommandContentProposalProvider.getContentProposals(GitCommandContentProposalProvider.java:35)
	at com.codeaffine.gonsole.internal.interpreter.ControlCommandInterpreter.lambda$1(ControlCommandInterpreter.java:100)
	at java.util.stream.ReferencePipeline$7$1.accept(Unknown Source)
	at java.util.stream.ReferencePipeline$2$1.accept(Unknown Source)
	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Unknown Source)
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
	at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
	at java.util.stream.AbstractPipeline.evaluateToArrayNode(Unknown Source)
	at java.util.stream.ReferencePipeline.toArray(Unknown Source)
	at com.codeaffine.gonsole.internal.interpreter.ControlCommandInterpreter.getRecognizedCommands(ControlCommandInterpreter.java:103)
	at com.codeaffine.gonsole.internal.interpreter.ControlCommandInterpreter.executeHelp(ControlCommandInterpreter.java:89)
	at com.codeaffine.gonsole.internal.interpreter.ControlCommandInterpreter.execute(ControlCommandInterpreter.java:48)
	at com.codeaffine.console.core.internal.ProcessorWorker.run(ProcessorWorker.java:45)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)


vdpolizei-sw> status
java.lang.IllegalStateException: Cannot set value to a final field 'com.codeaffine.gonsole.internal.interpreter.CommandInfo.arguments'.
	at org.kohsuke.args4j.spi.Setters.create(Setters.java:32)
	at org.kohsuke.args4j.ClassParser.parse(ClassParser.java:38)
	at org.kohsuke.args4j.CmdLineParser.<init>(CmdLineParser.java:96)
	at org.kohsuke.args4j.CmdLineParser.<init>(CmdLineParser.java:71)
	at org.eclipse.jgit.pgm.opt.CmdLineParser.<init>(CmdLineParser.java:133)
	at org.eclipse.jgit.pgm.opt.CmdLineParser.<init>(CmdLineParser.java:116)
	at com.codeaffine.gonsole.internal.interpreter.CommandLineParser.isRecognized(CommandLineParser.java:24)
	at com.codeaffine.gonsole.internal.interpreter.GitCommandInterpreter.isRecognized(GitCommandInterpreter.java:33)
	at com.codeaffine.console.core.internal.ProcessorWorker.run(ProcessorWorker.java:44)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
```

**Comment by pprossi** [comment]
Some additional informations:

Version: Photon Milestone 3 (4.8.0M3)
Build id: 20171102-1036
jre1.8.0_91

**Comment by rherrmann** [comment]
Thank's a lot for your hint. The root cause here seems to be that `org.kohsuke.args4j` does no longer allow to set final fields (see this commit: 
https://github.com/kohsuke/args4j/commit/6e11f89d40dcc518c0e5eb9eef5d74f05d58e6af). This library is used by Gonsole, as well as the underlying [JGit Pgm](https://wiki.eclipse.org/JGit/User_Guide#Running_the_JGit_CLI) to parse command line arguments.

With commit 84b50a8e982ccdca5f74fe490639565da4a9e512, Gonsole has been changed to be compatible with new versions of Args4J. JGit has also done some changes (see this change request: https://git.eclipse.org/r/#/c/104304/2) to prevent this exception, but not all commands have been adapted accordingly. 

I have proposed this change https://git.eclipse.org/r/111850 to fix the (hopefully only) remaining place.

Once this change is accepted, and after updating Gonsole, you may want to install (_Help_ > _Install New Software..._) the newest, not yet released, JGit version from here: http://download.eclipse.org/egit/updates-nightly
