### ISSUE TITLE
gonsole Console is no longer accessible

### ISSUE THREAD

**Issue by rwellman-ats** [rherrmann/gonsole#82]
When I try to select the gonsole Console in the dropdown, I click it but nothing happens.  This worked when I originally installed it about a month ago.  I don't use it a ton (though I do like it) so I don't know specifically when this started happening.  My workspace/Eclipse has been fairly stable since it was working (i.e. I don't think I've installed other plugins, etc.)

I wish I could tell you more but I have no idea how to troubleshoot this.  Restarting Eclipse doesn't help, etc.  If you can provide guidance on how to obtain more info, I am glad to help.  For now, there is not even an error dialog.

FWIW, I am using STS on Windows10:
Spring Tool Suite 4 
Version: 4.11.0.RELEASE
Build Id: 202106180608

**Comment by rherrmann** [comment]
Do you see any message in the _Error Log_ view that could relate to the problem?

If there is nothing related, I can only suggest workarounds like deleting Gonsole's state location (`<workspace_folder>/.metadata/.plugins/com.codeaffine.gonsole`) or uninstalling and then reinstalling the plug-in.

**Comment by rwellman-ats** [comment]
ahhh... (I should have known about that)... here is a screenshot and stack trace:

eclipse.buildId=4.11.0.202106180608
java.version=16.0.1
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en_US
Framework arguments:  -product org.springframework.boot.ide.branding.sts4
Command-line arguments:  -os win32 -ws win32 -arch x86_64 -product org.springframework.boot.ide.branding.sts4


java.lang.NoSuchMethodError: 'org.eclipse.egit.core.RepositoryUtil org.eclipse.egit.core.Activator.getRepositoryUtil()'
	at com.codeaffine.gonsole.egit.internal.EGitFacade.<init>(EGitFacade.java:18)
	at com.codeaffine.gonsole.egit.internal.repositores.EGitRepositoryProvider.getRepositoryLocations(EGitRepositoryProvider.java:14)
	at com.codeaffine.gonsole.internal.repository.CompositeRepositoryProvider.stream(CompositeRepositoryProvider.java:60)
	at com.codeaffine.gonsole.internal.repository.CompositeRepositoryProvider.lambda$0(CompositeRepositoryProvider.java:28)
	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:273)
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
	at com.codeaffine.gonsole.internal.repository.CompositeRepositoryProvider.getRepositoryLocations(CompositeRepositoryProvider.java:29)
	at com.codeaffine.gonsole.internal.repository.CompositeRepositoryProviderFactory.updateCurrentRepositoryLocation(CompositeRepositoryProviderFactory.java:27)
	at com.codeaffine.gonsole.internal.repository.CompositeRepositoryProviderFactory.create(CompositeRepositoryProviderFactory.java:22)
	at com.codeaffine.gonsole.GitConsoleFactory.createCompositeRepositoryProvider(GitConsoleFactory.java:32)
	at com.codeaffine.gonsole.GitConsoleFactory.getConsoleConfigurer(GitConsoleFactory.java:27)
	at com.codeaffine.console.core.ConsoleFactory.createConsole(ConsoleFactory.java:30)
	at com.codeaffine.console.core.ConsoleFactory.openConsole(ConsoleFactory.java:24)
	at org.eclipse.ui.internal.console.OpenConsoleAction$ConsoleFactoryAction.run(OpenConsoleAction.java:153)
	at org.eclipse.ui.internal.console.OpenConsoleAction$ConsoleFactoryAction.runWithEvent(OpenConsoleAction.java:161)
	at org.eclipse.jface.action.ActionContributionItem.handleWidgetSelection(ActionContributionItem.java:580)
	at org.eclipse.jface.action.ActionContributionItem.lambda$4(ActionContributionItem.java:414)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4209)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1043)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4026)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3626)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1157)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1046)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:644)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:551)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:156)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:152)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:401)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:654)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:591)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1462)



![image](https://user-images.githubusercontent.com/85251807/128366683-50386b61-1304-4324-b648-b2ce3d67bc81.png)

**Comment by rherrmann** [comment]
Could you find out which version of EGit is packaged with your IDE? IIRC, the _About_ dialog has a _Plug-ins_ tab that lists all plug-ins and their respective version.

**Comment by rwellman-ats** [comment]
Eclipse EGit	Git integration for Eclipse	5.12.0.202106070339-r	org.eclipse.egit

![image](https://user-images.githubusercontent.com/85251807/128421959-76e1b1cd-abe6-427b-93ec-3c85c6c19430.png)

**Comment by rherrmann** [comment]
To integrate with EGit, Gonsole asks for a list of repositories known to EGit. It seems as if in recent versions of EGit, this API was changed. I will try to work around this change and provide an update of Gonsole.

**Comment by rherrmann** [comment]
Resolving the actual problem was rather straightforward. However, the code wasn't touched for years and the build must have stopped working in between. Updating dependencies and bringing the build back took a considerable amount of time. Tough the build works now, some UI tests that simulate keyboard interaction still fail. I'm not able to invest more time.

Given the low amount of users and in contrast thereof, the large effort it takes to keep the project up-to-date, with my my co-maintainer, we decided to end this project. If, against all odds, someone want's to take ownership of this project, we'd be happy to hand it over.
